### ISSUE TITLE
Daemon Release workflow RED: companion fails windows/amd64 cross-compile (syscall.Kill / SysProcAttr.Setpgid) — daemon-v0.8.6 (#106)

### ISSUE THREAD

**Issue by eliteGoblin** [eliteGoblin/focusd#108]
## Symptom
The **Daemon Release** GitHub Actions workflow fails at the `Build + sign (darwin arm64/amd64)` step for tag `daemon-v0.8.6`. The job exits 1 at the **companion** cross-compile for the `windows/amd64` matrix target; it never reaches the `Publish GitHub Release` step (so the #105 already-exists publish-skip never runs).

Run: https://github.com/eliteGoblin/focusd/actions/runs/29627572412 (job `release`, RED).

## Observed (exact CI error)
```
building companion (windows/amd64) -> .../daemon/internal/osadapter/companiondata/companion
# github.com/eliteGoblin/focusd/daemon/cmd/companion
cmd/companion/main.go:92:41: unknown field Setpgid in struct literal of type syscall.SysProcAttr
cmd/companion/main.go:97:22: undefined: syscall.Kill
##[error]Process completed with exit code 1.
```

## Local reproduction
```
cd daemon
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o /dev/null ./cmd/companion ; echo exit=$?
# exit=1  (Setpgid + syscall.Kill)
CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -o /dev/null ./cmd/companion ; echo exit=$?  # exit=0
CGO_ENABLED=0 GOOS=linux   GOARCH=arm64 go build -o /dev/null ./cmd/companion ; echo exit=$?  # exit=0
CGO_ENABLED=0 GOOS=darwin  GOARCH=arm64 go build -o /dev/null ./cmd/companion ; echo exit=$?  # exit=0
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o /dev/null ./cmd/daemon    ; echo exit=$?  # exit=0
```

## Source
`daemon/cmd/companion/main.go` `execWatchdogCtx` (introduced by #106 companion rail self-sustain) uses unix-only APIs unconditionally, no build tag / no platform-split sibling:
- line 92: `cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}`
- line 97: `syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)`

`syscall.SysProcAttr` has no `Setpgid` field on windows and `syscall.Kill` is undefined on windows.

## Scope
- companion: darwin/arm64, darwin/amd64, linux/amd64, linux/arm64 = BUILD OK; **windows/amd64 = FAIL**.
- daemon binary (`./cmd/daemon`): windows/amd64 = BUILD OK (unaffected).
- The Daemon Release workflow builds the companion for the full matrix (`targets="darwin/arm64 darwin/amd64 linux/amd64 linux/arm64 windows/amd64"`, .github/workflows/daemon-release.yml), so the windows companion break turns the whole release job RED.

## Expected
The workflow comment states linux/windows are "future-ready" and expected to build+sign today (CGO-free). The companion should cross-compile to windows/amd64 (guard the process-group/kill logic behind a build tag or a platform-split file), keeping the Daemon Release job green.

## Impact (this deploy)
- Live darwin/arm64 deploy of v0.19.6 / daemon-v0.8.6 is GREEN and unaffected.
- Manual release publish of the darwin/arm64 asset (`daemon-darwin-arm64`) succeeded and verifies.
- Only the CI Daemon Release job is RED (windows/amd64 companion). The published darwin asset the deploy uses is intact.

## Version tested
daemon-v0.8.6 / platform v0.19.6, source origin/master @ eccb9a5.
TC ref: release-CI gate for the v0.19.6 / daemon-v0.8.6 deploy.
